@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = '1.1.0'
String imgTag  = "v" + version + "-1"

olcnePipeline(
        branchPattern: new BranchPattern(master: '(master|release/.*)', feature: '(?!^master$)(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/cert-manager-webhook-oci:' + imgTag): 'olcne/cert-manager-webhook-oci:' + imgTag],
        platforms: ['ol8'],
        architectures: ['x86_64', 'aarch64'],
        publishImage: false,
        noSlim: [],
)
